# coding: utf-8

"""
    jans-config-api

    jans-config-api - Authorization services  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: xxx@gluu.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class InlineResponse2003(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'servers': 'str',
        'max_operation_queue_length': 'int',
        'buffer_size': 'int',
        'default_put_expiration': 'int',
        'memcached_connection_factory_type': 'str'
    }

    attribute_map = {
        'servers': 'servers',
        'max_operation_queue_length': 'maxOperationQueueLength',
        'buffer_size': 'bufferSize',
        'default_put_expiration': 'defaultPutExpiration',
        'memcached_connection_factory_type': 'memcachedConnectionFactoryType'
    }

    def __init__(self, servers=None, max_operation_queue_length=99999999, buffer_size=32768, default_put_expiration=60, memcached_connection_factory_type=None):  # noqa: E501
        """InlineResponse2003 - a model defined in Swagger"""  # noqa: E501
        self._servers = None
        self._max_operation_queue_length = None
        self._buffer_size = None
        self._default_put_expiration = None
        self._memcached_connection_factory_type = None
        self.discriminator = None
        self.servers = servers
        self.max_operation_queue_length = max_operation_queue_length
        self.buffer_size = buffer_size
        self.default_put_expiration = default_put_expiration
        self.memcached_connection_factory_type = memcached_connection_factory_type

    @property
    def servers(self):
        """Gets the servers of this InlineResponse2003.  # noqa: E501

        Server details separated by spaces.  # noqa: E501

        :return: The servers of this InlineResponse2003.  # noqa: E501
        :rtype: str
        """
        return self._servers

    @servers.setter
    def servers(self, servers):
        """Sets the servers of this InlineResponse2003.

        Server details separated by spaces.  # noqa: E501

        :param servers: The servers of this InlineResponse2003.  # noqa: E501
        :type: str
        """
        if servers is None:
            raise ValueError("Invalid value for `servers`, must not be `None`")  # noqa: E501

        self._servers = servers

    @property
    def max_operation_queue_length(self):
        """Gets the max_operation_queue_length of this InlineResponse2003.  # noqa: E501

        Maximum operation Queue Length.  # noqa: E501

        :return: The max_operation_queue_length of this InlineResponse2003.  # noqa: E501
        :rtype: int
        """
        return self._max_operation_queue_length

    @max_operation_queue_length.setter
    def max_operation_queue_length(self, max_operation_queue_length):
        """Sets the max_operation_queue_length of this InlineResponse2003.

        Maximum operation Queue Length.  # noqa: E501

        :param max_operation_queue_length: The max_operation_queue_length of this InlineResponse2003.  # noqa: E501
        :type: int
        """
        if max_operation_queue_length is None:
            raise ValueError("Invalid value for `max_operation_queue_length`, must not be `None`")  # noqa: E501

        self._max_operation_queue_length = max_operation_queue_length

    @property
    def buffer_size(self):
        """Gets the buffer_size of this InlineResponse2003.  # noqa: E501

        Buffer Size.  # noqa: E501

        :return: The buffer_size of this InlineResponse2003.  # noqa: E501
        :rtype: int
        """
        return self._buffer_size

    @buffer_size.setter
    def buffer_size(self, buffer_size):
        """Sets the buffer_size of this InlineResponse2003.

        Buffer Size.  # noqa: E501

        :param buffer_size: The buffer_size of this InlineResponse2003.  # noqa: E501
        :type: int
        """
        if buffer_size is None:
            raise ValueError("Invalid value for `buffer_size`, must not be `None`")  # noqa: E501

        self._buffer_size = buffer_size

    @property
    def default_put_expiration(self):
        """Gets the default_put_expiration of this InlineResponse2003.  # noqa: E501

        Expiration timeout value.  # noqa: E501

        :return: The default_put_expiration of this InlineResponse2003.  # noqa: E501
        :rtype: int
        """
        return self._default_put_expiration

    @default_put_expiration.setter
    def default_put_expiration(self, default_put_expiration):
        """Sets the default_put_expiration of this InlineResponse2003.

        Expiration timeout value.  # noqa: E501

        :param default_put_expiration: The default_put_expiration of this InlineResponse2003.  # noqa: E501
        :type: int
        """
        if default_put_expiration is None:
            raise ValueError("Invalid value for `default_put_expiration`, must not be `None`")  # noqa: E501

        self._default_put_expiration = default_put_expiration

    @property
    def memcached_connection_factory_type(self):
        """Gets the memcached_connection_factory_type of this InlineResponse2003.  # noqa: E501

        The MemcachedConnectionFactoryType Type.  # noqa: E501

        :return: The memcached_connection_factory_type of this InlineResponse2003.  # noqa: E501
        :rtype: str
        """
        return self._memcached_connection_factory_type

    @memcached_connection_factory_type.setter
    def memcached_connection_factory_type(self, memcached_connection_factory_type):
        """Sets the memcached_connection_factory_type of this InlineResponse2003.

        The MemcachedConnectionFactoryType Type.  # noqa: E501

        :param memcached_connection_factory_type: The memcached_connection_factory_type of this InlineResponse2003.  # noqa: E501
        :type: str
        """
        if memcached_connection_factory_type is None:
            raise ValueError("Invalid value for `memcached_connection_factory_type`, must not be `None`")  # noqa: E501
        allowed_values = ["DEFAULT", "BINARY"]  # noqa: E501
        if memcached_connection_factory_type not in allowed_values:
            raise ValueError(
                "Invalid value for `memcached_connection_factory_type` ({0}), must be one of {1}"  # noqa: E501
                .format(memcached_connection_factory_type, allowed_values)
            )

        self._memcached_connection_factory_type = memcached_connection_factory_type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse2003, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse2003):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
