# coding: utf-8

"""
    jans-config-api

    jans-config-api - Authorization services  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: xxx@gluu.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.configuration__fido2_api import ConfigurationFido2Api  # noqa: E501
from swagger_client.rest import ApiException


class TestConfigurationFido2Api(unittest.TestCase):
    """ConfigurationFido2Api unit test stubs"""

    def setUp(self):
        self.api = ConfigurationFido2Api()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_properties_fido2(self):
        """Test case for get_properties_fido2

        Gets Jans Authorization Server Fido2 configuration properties.  # noqa: E501
        """
        pass

    def test_put_properties_fido2(self):
        """Test case for put_properties_fido2

        Updates Fido2 configuration properties.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
