# coding: utf-8

"""
    jans-config-api

    jans-config-api - Authorization services  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: xxx@gluu.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.o_auth___open_id_connect___clients_api import OAuthOpenIDConnectClientsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestOAuthOpenIDConnectClientsApi(unittest.TestCase):
    """OAuthOpenIDConnectClientsApi unit test stubs"""

    def setUp(self):
        self.api = OAuthOpenIDConnectClientsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_oauth_openid_clients_by_inum(self):
        """Test case for delete_oauth_openid_clients_by_inum

        Delete OpenId Connect client.  # noqa: E501
        """
        pass

    def test_get_oauth_openid_clients(self):
        """Test case for get_oauth_openid_clients

        Gets list of OpenID Connect clients  # noqa: E501
        """
        pass

    def test_get_oauth_openid_clients_by_inum(self):
        """Test case for get_oauth_openid_clients_by_inum

        Get OpenId Connect Client by Inum  # noqa: E501
        """
        pass

    def test_patch_oauth_openid_clients_by_inum(self):
        """Test case for patch_oauth_openid_clients_by_inum

        Update modified properties of OpenId Connect client by Inum.  # noqa: E501
        """
        pass

    def test_post_oauth_openid_clients(self):
        """Test case for post_oauth_openid_clients

        Create new OpenId connect client  # noqa: E501
        """
        pass

    def test_put_oauth_openid_clients(self):
        """Test case for put_oauth_openid_clients

        Update OpenId Connect client.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
