# coding: utf-8

"""
    jans-config-api

    jans-config-api - Authorization services  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: xxx@gluu.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.o_auth___open_id_connect___sector_identifiers_api import OAuthOpenIDConnectSectorIdentifiersApi  # noqa: E501
from swagger_client.rest import ApiException


class TestOAuthOpenIDConnectSectorIdentifiersApi(unittest.TestCase):
    """OAuthOpenIDConnectSectorIdentifiersApi unit test stubs"""

    def setUp(self):
        self.api = OAuthOpenIDConnectSectorIdentifiersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_oauth_openid_sectors_by_id(self):
        """Test case for delete_oauth_openid_sectors_by_id

        Delete OpenID Connect Sector.  # noqa: E501
        """
        pass

    def test_get_oauth_openid_sectors(self):
        """Test case for get_oauth_openid_sectors

        Gets list of OpenID Connect Sectors.  # noqa: E501
        """
        pass

    def test_get_oauth_openid_sectors_by_id(self):
        """Test case for get_oauth_openid_sectors_by_id

        Get OpenID Connect Sector by Inum.  # noqa: E501
        """
        pass

    def test_patch_oauth_openid_sectors_by_id(self):
        """Test case for patch_oauth_openid_sectors_by_id

        Partially update OpenId Connect Sector by Inum.  # noqa: E501
        """
        pass

    def test_post_oauth_openid_sectors(self):
        """Test case for post_oauth_openid_sectors

        Create new OpenID Connect Sector.  # noqa: E501
        """
        pass

    def test_put_oauth_openid_sectors(self):
        """Test case for put_oauth_openid_sectors

        Update OpenId Connect Sector.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
