# coding: utf-8

"""
    jans-config-api

    jans-config-api - Authorization services  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: xxx@gluu.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.configuration__smtp_api import ConfigurationSMTPApi  # noqa: E501
from swagger_client.rest import ApiException


class TestConfigurationSMTPApi(unittest.TestCase):
    """ConfigurationSMTPApi unit test stubs"""

    def setUp(self):
        self.api = ConfigurationSMTPApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_config_smtp(self):
        """Test case for delete_config_smtp

        Deletes SMTP server configuration.  # noqa: E501
        """
        pass

    def test_get_config_smtp(self):
        """Test case for get_config_smtp

        Returns SMTP server configuration.  # noqa: E501
        """
        pass

    def test_post_config_smtp(self):
        """Test case for post_config_smtp

        Adds SMTP server configuration.  # noqa: E501
        """
        pass

    def test_put_config_smtp(self):
        """Test case for put_config_smtp

        Updates SMTP server configuration.  # noqa: E501
        """
        pass

    def test_test_config_smtp(self):
        """Test case for test_config_smtp

        Test SMTP server configuration.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
