# coding: utf-8

"""
    jans-config-api

    jans-config-api - Authorization services  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: xxx@gluu.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.custom_script_script_error import CustomScriptScriptError  # noqa: E501
from swagger_client.rest import ApiException


class TestCustomScriptScriptError(unittest.TestCase):
    """CustomScriptScriptError unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCustomScriptScriptError(self):
        """Test CustomScriptScriptError"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.custom_script_script_error.CustomScriptScriptError()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
