# coding: utf-8

"""
    jans-config-api

    jans-config-api - Authorization services  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: xxx@gluu.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.configuration__jwk___json_web_key__jwk_api import ConfigurationJWKJSONWebKeyJWKApi  # noqa: E501
from swagger_client.rest import ApiException


class TestConfigurationJWKJSONWebKeyJWKApi(unittest.TestCase):
    """ConfigurationJWKJSONWebKeyJWKApi unit test stubs"""

    def setUp(self):
        self.api = ConfigurationJWKJSONWebKeyJWKApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_config_jwks(self):
        """Test case for get_config_jwks

        Gets list of JSON Web Key (JWK) used by server.  # noqa: E501
        """
        pass

    def test_patch_config_jwks(self):
        """Test case for patch_config_jwks

        Patch JWKS  # noqa: E501
        """
        pass

    def test_put_config_jwks(self):
        """Test case for put_config_jwks

        Puts/replaces JWKS  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
