# coding: utf-8

"""
    jans-config-api

    jans-config-api - Authorization services  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: xxx@gluu.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.default_authentication_method_api import DefaultAuthenticationMethodApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDefaultAuthenticationMethodApi(unittest.TestCase):
    """DefaultAuthenticationMethodApi unit test stubs"""

    def setUp(self):
        self.api = DefaultAuthenticationMethodApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_acrs(self):
        """Test case for get_acrs

        Gets default authentication method.  # noqa: E501
        """
        pass

    def test_put_acrs(self):
        """Test case for put_acrs

        Updates default authentication method.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
