# coding: utf-8

"""
    jans-config-api

    jans-config-api - Authorization services  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: xxx@gluu.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.cache_configuration__memcached_api import CacheConfigurationMemcachedApi  # noqa: E501
from swagger_client.rest import ApiException


class TestCacheConfigurationMemcachedApi(unittest.TestCase):
    """CacheConfigurationMemcachedApi unit test stubs"""

    def setUp(self):
        self.api = CacheConfigurationMemcachedApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_config_cache_memcached(self):
        """Test case for get_config_cache_memcached

        Returns Memcached cache configuration.  # noqa: E501
        """
        pass

    def test_put_config_cache_memcached(self):
        """Test case for put_config_cache_memcached

        Updates Memcached cache configuration.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
