# coding: utf-8

"""
    jans-config-api

    jans-config-api - Authorization services  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: xxx@gluu.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.open_id_connect_client_details_ import OpenIDConnectClientDetails_  # noqa: E501
from swagger_client.rest import ApiException


class TestOpenIDConnectClientDetails_(unittest.TestCase):
    """OpenIDConnectClientDetails_ unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOpenIDConnectClientDetails_(self):
        """Test OpenIDConnectClientDetails_"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.open_id_connect_client_details_.OpenIDConnectClientDetails_()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
