# coding: utf-8

"""
    jans-config-api

    jans-config-api - Authorization services  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: xxx@gluu.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.database___ldap_configuration_api import DatabaseLDAPConfigurationApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDatabaseLDAPConfigurationApi(unittest.TestCase):
    """DatabaseLDAPConfigurationApi unit test stubs"""

    def setUp(self):
        self.api = DatabaseLDAPConfigurationApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_config_database_ldap_by_name(self):
        """Test case for delete_config_database_ldap_by_name

        Deletes an LDAP configuration.  # noqa: E501
        """
        pass

    def test_get_config_database_ldap(self):
        """Test case for get_config_database_ldap

        Gets list of existing LDAP configurations.  # noqa: E501
        """
        pass

    def test_get_config_database_ldap_by_name(self):
        """Test case for get_config_database_ldap_by_name

        Gets an LDAP configuration by name.  # noqa: E501
        """
        pass

    def test_patch_config_database_ldap_by_name(self):
        """Test case for patch_config_database_ldap_by_name

        Partially modify an LDAP configuration.  # noqa: E501
        """
        pass

    def test_post_config_database_ldap(self):
        """Test case for post_config_database_ldap

        Adds a new LDAP configuration.  # noqa: E501
        """
        pass

    def test_post_config_database_ldap_test(self):
        """Test case for post_config_database_ldap_test

        Tests a LDAP configurations by name.  # noqa: E501
        """
        pass

    def test_put_config_database_ldap(self):
        """Test case for put_config_database_ldap

        Updates LDAP configuration.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
