# coding: utf-8

"""
    jans-config-api

    jans-config-api - Authorization services  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: xxx@gluu.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.attribute_api import AttributeApi  # noqa: E501
from swagger_client.rest import ApiException


class TestAttributeApi(unittest.TestCase):
    """AttributeApi unit test stubs"""

    def setUp(self):
        self.api = AttributeApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_attributes_by_inum(self):
        """Test case for delete_attributes_by_inum

        Deletes an attribute based on inum.  # noqa: E501
        """
        pass

    def test_get_attributes(self):
        """Test case for get_attributes

        Gets a list of Gluu attributes.  # noqa: E501
        """
        pass

    def test_get_attributes_by_inum(self):
        """Test case for get_attributes_by_inum

        Gets an attribute based on inum.  # noqa: E501
        """
        pass

    def test_patch_attributes_by_inum(self):
        """Test case for patch_attributes_by_inum

        Partially modify a GluuAttribute.  # noqa: E501
        """
        pass

    def test_post_attributes(self):
        """Test case for post_attributes

        Adds a new attribute.  # noqa: E501
        """
        pass

    def test_put_attributes(self):
        """Test case for put_attributes

        Updates an existing attribute.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
