# coding: utf-8

"""
    jans-config-api

    jans-config-api - Authorization services  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: xxx@gluu.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.database___couchbase_configuration_api import DatabaseCouchbaseConfigurationApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDatabaseCouchbaseConfigurationApi(unittest.TestCase):
    """DatabaseCouchbaseConfigurationApi unit test stubs"""

    def setUp(self):
        self.api = DatabaseCouchbaseConfigurationApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_config_database_couchbase_by_name(self):
        """Test case for delete_config_database_couchbase_by_name

        Deletes a Couchbase configurations by name.  # noqa: E501
        """
        pass

    def test_get_config_database_couchbase(self):
        """Test case for get_config_database_couchbase

        Gets list of existing Couchbase configurations.  # noqa: E501
        """
        pass

    def test_get_config_database_couchbase_by_name(self):
        """Test case for get_config_database_couchbase_by_name

        Gets a Couchbase configurations by name.  # noqa: E501
        """
        pass

    def test_patch_config_database_couchbase_by_name(self):
        """Test case for patch_config_database_couchbase_by_name

        Partially modify an Couchbase configuration.  # noqa: E501
        """
        pass

    def test_post_config_database_couchbase(self):
        """Test case for post_config_database_couchbase

        Adds a new Couchbase configuration.  # noqa: E501
        """
        pass

    def test_post_config_database_couchbase_test(self):
        """Test case for post_config_database_couchbase_test

        Tests a Couchbase configurations by name.  # noqa: E501
        """
        pass

    def test_put_config_database_couchbase(self):
        """Test case for put_config_database_couchbase

        Updates Couchbase configuration.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
