# coding: utf-8

"""
    jans-config-api

    jans-config-api - Authorization services  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: xxx@gluu.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.inline_response2002_native_persistence_configuration import InlineResponse2002NativePersistenceConfiguration  # noqa: E501
from swagger_client.rest import ApiException


class TestInlineResponse2002NativePersistenceConfiguration(unittest.TestCase):
    """InlineResponse2002NativePersistenceConfiguration unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse2002NativePersistenceConfiguration(self):
        """Test InlineResponse2002NativePersistenceConfiguration"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.inline_response2002_native_persistence_configuration.InlineResponse2002NativePersistenceConfiguration()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
