# coding: utf-8

"""
    jans-config-api

    jans-config-api - Authorization services  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: xxx@gluu.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.authentication_method1 import AuthenticationMethod1  # noqa: E501
from swagger_client.rest import ApiException


class TestAuthenticationMethod1(unittest.TestCase):
    """AuthenticationMethod1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAuthenticationMethod1(self):
        """Test AuthenticationMethod1"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.authentication_method1.AuthenticationMethod1()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
