# coding: utf-8

"""
    jans-config-api

    jans-config-api - Authorization services  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: xxx@gluu.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.o_auth___uma_resources_api import OAuthUMAResourcesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestOAuthUMAResourcesApi(unittest.TestCase):
    """OAuthUMAResourcesApi unit test stubs"""

    def setUp(self):
        self.api = OAuthUMAResourcesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_oauth_uma_resources_by_id(self):
        """Test case for delete_oauth_uma_resources_by_id

        Deletes an UMA resource.  # noqa: E501
        """
        pass

    def test_get_oauth_uma_resources(self):
        """Test case for get_oauth_uma_resources

        Gets list of UMA resources.  # noqa: E501
        """
        pass

    def test_get_oauth_uma_resources_by_id(self):
        """Test case for get_oauth_uma_resources_by_id

        Gets an UMA resource by ID.  # noqa: E501
        """
        pass

    def test_patch_oauth_uma_resources_by_id(self):
        """Test case for patch_oauth_uma_resources_by_id

        Partially updates an UMA resource by Inum.  # noqa: E501
        """
        pass

    def test_post_oauth_uma_resources(self):
        """Test case for post_oauth_uma_resources

        Creates an UMA resource.  # noqa: E501
        """
        pass

    def test_put_oauth_uma_resources(self):
        """Test case for put_oauth_uma_resources

        Updates an UMA resource.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
