# coding: utf-8

"""
    jans-config-api

    jans-config-api - Authorization services  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: xxx@gluu.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.custom_scripts_api import CustomScriptsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestCustomScriptsApi(unittest.TestCase):
    """CustomScriptsApi unit test stubs"""

    def setUp(self):
        self.api = CustomScriptsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_config_scripts_by_inum(self):
        """Test case for delete_config_scripts_by_inum

        Deletes a custom script.  # noqa: E501
        """
        pass

    def test_get_config_scripts(self):
        """Test case for get_config_scripts

        Gets a list of custom scripts.  # noqa: E501
        """
        pass

    def test_get_config_scripts_by_inum(self):
        """Test case for get_config_scripts_by_inum

        Gets a script by Inum.  # noqa: E501
        """
        pass

    def test_get_config_scripts_by_type(self):
        """Test case for get_config_scripts_by_type

        Gets list of scripts by type.  # noqa: E501
        """
        pass

    def test_post_config_scripts(self):
        """Test case for post_config_scripts

        Adds a new custom script.  # noqa: E501
        """
        pass

    def test_put_config_scripts(self):
        """Test case for put_config_scripts

        Updates a custom script.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
