# coding: utf-8

"""
    jans-config-api

    jans-config-api - Authorization services  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: xxx@gluu.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.web_keys_configuration1 import WebKeysConfiguration1  # noqa: E501
from swagger_client.rest import ApiException


class TestWebKeysConfiguration1(unittest.TestCase):
    """WebKeysConfiguration1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWebKeysConfiguration1(self):
        """Test WebKeysConfiguration1"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.web_keys_configuration1.WebKeysConfiguration1()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
